name: Update Data and Figures

on:
  schedule:
    - cron: "20 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update Figures
        env:
          SODAPY_APPTOKEN: ${{secrets.SODAPY_APPTOKEN}}
        run: python update-data-and-figures.py
      - name: push changes to remote
        run: |
          git config --global user.name "${{secrets.USER_NAME}}"
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git add ny-counties-geo.js site-last-updated best_5.js worst_5.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "update data and figures"; git push)
