name: Update Data

on:
  schedule:
    - cron: "* 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.5"
          architecture: "x64"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
