name: Update Figures

on:
  schedule:
    - cron: "*/42 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update Figures
        run: python update_figures.py
      - name: push changes to remote
        run: |
          git config --global user.name "${{secrets.USER_NAME}}"
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git add index.html
          git commit -m "update figures"
          git push
